apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-app-deployment
  labels:
    app: marketplace-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketplace-app
  template:
    metadata:
      labels:
        app: marketplace-app
    spec:
      containers:
        - name: marketplace-app
          image: marketplace-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "marketplace-postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "app_db"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASS
              value: "postgres"
            - name: JWT_SECRET
              value: "change_me"
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-postgres-deployment
  labels:
    app: marketplace-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketplace-postgres
  template:
    metadata:
      labels:
        app: marketplace-postgres
    spec:
      containers:
        - name: marketplace-postgres
          image: postgres:16
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              value: "app_db"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          ports:
            - containerPort: 5432