apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-v2
  labels:
    app: marketplace-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-postgres
  labels:
    app: marketplace-postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: marketplace-postgres
  template:
    metadata:
      labels:
        app: marketplace-postgres
    spec:
      containers:
        - name: marketplace-postgres
          image: postgres:16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "app_db"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASS
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-v2
---
apiVersion: v1
kind: Service
metadata:
  name: marketplace-postgres
  labels:
    app: marketplace-postgres
spec:
  type: LoadBalancer
  selector:
    app: marketplace-postgres
  ports:
    - name: postgres
      port: 5433
      targetPort: 5432
      protocol: TCP
