apiVersion: v1
kind: Service
metadata:
  name: marketplace-app-service
  labels:
    app: marketplace-app
spec:
  type: NodePort
  selector:
    app: marketplace-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: marketplace-postgres-service
  labels:
    app: marketplace-postgres
spec:
  type: ClusterIP
  selector:
    app: marketplace-postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP